name: Blog CI/CD

# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  push:
    branches: 
      - hexo-blog-source

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install hexo-cli  -g
        npm install gulp -g
        npm install

    - name: Generate files
      # 编译 markdown 文件
      run: |
        hexo clean
        hexo generate

    # - name: Execute gulp task
    #   run: gulp

    - name: Deploy hexo blog
      env: 
        # Github 仓库
        GITHUB_REPO: github.com/hyq965672903/hyq965672903.github.io
        # Gitee 仓库
        GITEE_REPO: gitee.com/hyq965672903/hyq965672903
      # 将编译后的博客文件推送到指定仓库
      run: |
        cd ./public && git init && git add .
        git config --global http.sslverify "false"
        git config --global url.“https://”.insteadOf git://
        git config user.name "hyq"
        git config user.email "965672903@qq.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://oauth2:@${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
        #  git push --force --quiet "http://hyq965672903:${{ secrets.GITEE_ACCESS_TOKEN }}@$GITEE_REPO" master:master
